Repository cloudera-labs/cloudera.cloud, pull requests merged in 2023-11, with the labels that each got.

#92 Update env_idbroker return value to 'idbroker' from 'mappings'
  plugins/modules/env_idbroker.py
Labels: bug

#128 Update collection version to 2.1.0
  galaxy.yml
Labels: enhancement, validated

#130 Fix malformed return value in API docs
  plugins/modules/datahub_cluster_recipe.py
Labels: documentation

#132 Update AWS subnet parameter names for CDW cluster creation
  plugins/modules/dw_cluster.py
Labels: bug, validated

#133 Add private_cluster parameters
  plugins/modules/de.py
  plugins/modules/df_service.py
  plugins/modules/ml.py
Labels: enhancement, validated
