Repository cloudera-labs/cloudera.cloud, pull requests merged in 2023-06, with the labels that each got.

#93 Update multiAz parameter docs
  plugins/modules/datalake.py
Labels: documentation, validated

#98 Add lookup plugins for DL and DH
  plugins/lookup/cdp_service.py
  plugins/lookup/datahub_definition.py
  plugins/lookup/datahub_instance.py
  plugins/lookup/datahub_service.py
  plugins/lookup/datahub_template.py
  plugins/lookup/datalake_runtime.py
  plugins/lookup/datalake_service.py
Labels: enhancement, validated

#94 Update payload to use clusterDefinition and clusterTemplate parameters
  plugins/modules/datahub_cluster.py
Labels: enhancement, validated

#100 Add FreeIPA lookup plugins
  plugins/lookup/env_freeipa_domain.py
  plugins/lookup/env_freeipa_hosts.py
Labels: enhancement, validated

#101 Add GCP region zones parameter
  plugins/modules/datahub_cluster.py
  plugins/modules/env.py
Labels: enhancement, validated

#102 Update creation parameters to reflect cloud provider specifics
  plugins/modules/datahub_cluster.py
Labels: bug, validated
