Repository cloudera-labs/cloudera.cloud, pull requests merged in 2024-05, with the labels that each got.

#143 Add analytics to API documents
  docsbuild/conf.py
Labels: documentation, validated

#144 Add module defaults groups
  meta/runtime.yml
Labels: enhancement, validated

#140 Add extra Azure parameters to cloudera.cloud.dw_cluster
  plugins/module_utils/cdp_common.py
  plugins/modules/dw_cluster.py
Labels: enhancement, validated

#146 Add template and image parameters to dw data viz module
  plugins/modules/dw_data_visualization.py
Labels: enhancement, validated

#145 Add autoscaling and impala_ha parameters to cdw vw module
  plugins/modules/dw_virtual_warehouse.py
Labels: enhancement

#147 Add Ansible Galaxy imports
  .github/workflows/publish_galaxy.yml
  .github/workflows/validate_pr.yml
  galaxy.yml
Labels: enhancement, validated

#148 Update to version 2.4.0
  docsbuild/antsibull-docs.cfg
  galaxy.yml
Labels: documentation, validated
