Repository cloudera-labs/cloudera.cloud, pull requests merged in 2024-06, with the labels that each got.

#152 Documentation examples updates
  plugins/modules/env.py
  plugins/modules/env_cred.py
Labels: documentation, validated

#154 Update module example typo
  plugins/modules/env_proxy.py
Labels: documentation, validated

#155 Add extra top-level parameters for CDW create cluster module
  plugins/modules/dw_cluster.py
Labels: enhancement, validated

#156 Update default value of use_ssd argument in CDE module
  plugins/modules/de.py
Labels: bug, validated
